name: "GitHub Actions Info"
run-name: "${{ github.actor }} is testing out GitHub Actions"
on: 
  push:
    branches: [master]
jobs:
  Testing: 
    runs-on: windows-latest
    env:
      creator: "Mirza Ghulam Rasyid"
    steps:
      - run: |
          write-output("Creator: ${{ env.creator}} ");
          write-output("The job was automatically trigger by a ${{ github.event_name }}");
          write-output("This job is running on a ${{ runner.os }} server hosted by GitHub!");
          write-output("Branch: ${{ github.ref }}. Repo: ${{ github.repository }}");
          write-output(${{ github }}|ConvertTo-JSON);
          write-output(${{ runner }}|ConvertTo-JSON);
        shell: powershell
        name: "Initial script run"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - run: write-output("The ${{ github.repository }} has been cloned to the runner")
      - run: Get-ChildItem "${{github.workspace}}"
        name: "Listing current directory"
      - run: write-output("The job status is ${{job.status}}");
      - run: write-output(${{ job }}|ConvertTo-JSON);
      
